Adjust style.

diff --git a/ddiropen b/ddiropen
--- a/ddiropen
+++ b/ddiropen
@@ -24,11 +24,11 @@
 # OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 # SOFTWARE.
 
-# Set default bookmark if there is none:
-BlankMark="---"
-
-ScriptName="${0##*/}"
+ScriptName=${0##*/}
 Version=1.0.0
+
+# Set default bookmark if there is none:
+BlankMark='---'
 
 # Compose the help message:
 HelpMessage="$ScriptName - Version: $Version
@@ -61,80 +61,75 @@ In the case where there's only one program and/or directory, they will be
 selected automatically.
 
 Usage examples:
-	$ScriptName \$HOME vifm,lf,sxiv
-	$ScriptName \ ranger,vifm
-	$ScriptName \"\$HOME/Pictures\" \"sxiv -t,sxiv -arf\"
-	$ScriptName \"\$HOME/Documents/dir-bookmarks.txt\" lf
-	$ScriptName \"\$HOME/Documents/dir-bookmarks.txt\" lf ###
+    $ScriptName \$HOME vifm,lf,sxiv
+    $ScriptName \ ranger,vifm
+    $ScriptName \"\$HOME/Pictures\" \"sxiv -t,sxiv -arf\"
+    $ScriptName \"\$HOME/Documents/dir-bookmarks.txt\" lf
+    $ScriptName \"\$HOME/Documents/dir-bookmarks.txt\" lf ###
 
 Example bookmarks file (keep in mind the tab separation):
 
-\$HOME	HM
-\"\$HOME/Pictures/Art References\"	AR
-\"\$XDG_CONFIG_HOME\"	CNF
-#\$COMMENT	CM	COMMENT: this can be whatever since it's not parsed.
-/mnt	MNT
-/etc	ETC
-/backup	BU
+\$HOME  HM
+\"\$HOME/Pictures/Art References\"  AR
+\"\$XDG_CONFIG_HOME\"   CNF
+#\$COMMENT  CM  COMMENT: this can be whatever since it's not parsed.
+/mnt    MNT
+/etc    ETC
+/backup     BU
 "
 
-suggest_help() {
-	printf "Try '%s --help' for more information.\n" "$ScriptName"
+suggest_help_and_exit() {
+    printf "Try '%s --help' for more information.\n" "$ScriptName"
+    exit 1
 }
 
-# Notify user of how to use the script:
-[ -z "$1" ] || [ "$1" = "-h" ] || [ "$1" = "--help" ] && \
-	printf "%s" "$HelpMessage" && \
-	exit 1
-
-# Print version and exit:
-[ "$1" = "-v" ] || [ "$1" = "--version" ] && \
-	printf "%s - Version: %s\n" "$ScriptName" "$Version" && \
-	exit 1
+case $1 in
+    '') printf '%s' "$HelpMessage"; exit 1;;
+    -h|--help) printf '%s' "$HelpMessage"; exit 0;;
+    -v|--version) printf '%s - Version: %s\n' "$ScriptName" "$Version"; exit 0;;
+esac
 
 # Set custom blank mark if it was set by the user:
-[ "$3" ] && BlankMark="$3"
+[ "$3" ] && BlankMark=$3
 
 # Set a location for the temporary file that holds the found directories:
 TempFile="/tmp/$ScriptName-dirs"
 
 # Set up a function that can be called to run in the background:
 find_directories() {
-	find "$1" -type d 2>/dev/null > "$TempFile"
-	printf "%s" "$ScriptName ENDofSEARCH" >> "$TempFile"
+    find "$1" -type d 2>/dev/null > "$TempFile"
+    printf '%s' "$ScriptName ENDofSEARCH" >> "$TempFile"
 }
 
 # Parse the passed programs:
-Parsed="$(printf "%s" "$2" | tr -s ',' '\n')"
+Parsed=$(printf '%s' "$2" | tr -s ',' '\n')
 
 # Count the amount of programs:
-ProgramAmount=$(printf "%s\n" "$Parsed" | wc -l)
+ProgramAmount=$(printf '%s\n' "$Parsed" | wc -l)
 
 # Determine whether the first argument is a directory or a file:
 if [ -d "$1" ]; then
-	Directory="$1"
-elif [ "$(file -i "$1" | awk '{printf $2}')" = "text/plain;" ]; then
-	cat "$1" | while IFS= read -r line; do
-		line="$(printf "%s" "$line" \
-			| awk -F '\t' -v blank="$BlankMark" \
-			'{print match($2, /[^ ]/) ? $2 : blank, $1}' OFS='\t')"
-		path="$(printf "%s" "$line" | awk -F '\t' '{printf $2}')"
-		eval [ -d "$path" ] 2>/dev/null \
-			&& printf "%s\n" "$line" >> "$TempFile"
-	done
-	if [ ! -s "$TempFile" ]; then
-		printf "ERROR: no valid directories in the specified file.\n"
-		suggest_help
-		exit 1
-	fi
-	[ $ProgramAmount = 1 ] && pn="[$Parsed] "
-	Directory="$(printf "%s" "$(cat "$TempFile")" \
-		| dmenu -i -l 30 -p "${pn}Select parent directory:" \
-		| awk -F '\t' '{printf $2}')"
+    Directory=$1
+elif [ "$(file -i "$1" | awk '{printf $2}')" = 'text/plain;' ]; then
+    cat "$1" | while IFS= read -r line; do
+        line=$(printf '%s' "$line" \
+            | awk -F '\t' -v blank=$BlankMark \
+            '{print match($2, /[^ ]/) ? $2 : blank, $1}' OFS='\t')
+        path=$(printf '%s' "$line" | awk -F '\t' '{printf $2}')
+        eval [ -d "$path" ] 2>/dev/null \
+            && printf '%s\n' "$line" >> "$TempFile"
+    done
+    if [ ! -s "$TempFile" ]; then
+        printf 'ERROR: no valid directories in the specified file.\n'
+        suggest_help_and_exit
+    fi
+    [ $ProgramAmount = 1 ] && pn="[$Parsed] "
+    Directory=$(printf '%s' "$(cat "$TempFile")" \
+        | dmenu -i -l 30 -p "${pn}Select parent directory:" \
+        | awk -F '\t' '{printf $2}')
 else
-	printf "ERROR: invalid first argument.\n"
-	suggest_help
-	exit 1
+    printf 'ERROR: invalid first argument.\n'
+    suggest_help_and_exit
 fi
 
 # Delete the temporary file:
@@ -148,26 +143,26 @@ eval find_directories "$Directory" &
 
 # If there's only one program, skip selecting it:
 if [ $ProgramAmount = 1 ]; then
-	Program="$Parsed"
+    Program=$Parsed
 # Else, select the program first to hide the time taken to find the directories:
 else
-	Program="$(printf "%s" "$Parsed" \
-		| dmenu -i -l 30 -p "Select program:")"
-	[ -z "$Program" ] && exit 1
+    Program=$(printf '%s' "$Parsed" \
+        | dmenu -i -l 30 -p 'Select program:')
+    [ -z "$Program" ] && exit 1
 fi
 
 # Wait until all directories have been found:
 until [ "$(tail -n 1 "$TempFile")" = "$ScriptName ENDofSEARCH" ]; do
-	sleep 0.1
+    sleep 0.1
 done
 
 # If there's only the result of the directory itself, select it:
 if [ $(wc -l "$TempFile" | awk '{printf $1}') = 1 ]; then
-	Chosen="$(sed '$d' "$TempFile")"
+    Chosen=$(sed '$d' "$TempFile")
 # Else, choose a directory:
 else
-	Chosen="$(sed '$d' "$TempFile" \
-		| dmenu -i -l 30 -p "[$Program] Select directory:")"
+    Chosen=$(sed '$d' "$TempFile" \
+        | dmenu -i -l 30 -p "[$Program] Select directory:")
 fi
 
 # Delete the temporary file:
diff --git a/dmarks b/dmarks
--- a/dmarks
+++ b/dmarks
@@ -24,7 +24,7 @@
 # OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 # SOFTWARE.
 
-ScriptName="${0##*/}"
+ScriptName=${0##*/}
 Version=1.0.0
 
 # Compose the help message:
@@ -43,200 +43,196 @@ One bookmark per line with three tab separated fields: URL, title and tags.
 The tags are comma separated and can have spaces.
 "
 
-# Notify user of how to use the script:
-[ -z "$1" ] || [ "$1" = "-h" ] || [ "$1" = "--help" ] && \
-	printf "%s" "$HelpMessage" && \
-	exit 1
-
-# Print version and exit:
-[ "$1" = "-v" ] || [ "$1" = "--version" ] && \
-	printf "%s - Version: %s\n" "$ScriptName" "$Version" && \
-	exit 1
+case $1 in
+    '') printf '%s' "$HelpMessage"; exit 1;;
+    -h|--help) printf '%s' "$HelpMessage"; exit 0;;
+    -v|--version) printf '%s' "$Version"; exit 0;;
+esac
 
 # Temporary file location
 TempFile="/tmp/$ScriptName"
 
 # Load and format the bookmarks:
-Bookmarks="$(cat "$1" | nl -n ln)"
-FormattedBookmarks="$(printf "%s" "$Bookmarks" \
-	| sed 's/\t\t/\tBLANK\t/' \
-	| awk -F '\t' '{print $1, $3, "("$4")", $5, "["$2"]"}')"
-	### For some reason setting OFS='\t' makes dmenu lag.
+Bookmarks=$(cat "$1" | nl -n ln)
+FormattedBookmarks=$(printf '%s' "$Bookmarks" \
+    | sed 's/\t\t/\tBLANK\t/' \
+    | awk -F '\t' '{print $1, $3, "("$4")", $5, "["$2"]"}')
+    ### For some reason setting OFS='\t' makes dmenu lag.
 
 # Set menu options:
-MenuOpen="1. Open a bookmark."
-MenuCreate="2. Create new bookmark."
-MenuEdit="3. Edit a bookmark."
-MenuDelete="4. Delete a bookmark."
+MenuOpen='1. Open a bookmark.'
+MenuCreate='2. Create new bookmark.'
+MenuEdit='3. Edit a bookmark.'
+MenuDelete='4. Delete a bookmark.'
 
 # Prompt user to choose action:
-ChosenMenu="$(printf "%s\n%s\n%s\n%s" \
-	"$MenuOpen" "$MenuCreate" "$MenuEdit" "$MenuDelete" \
-	| dmenu -i -l 10 -p "$ScriptName:")"
+ChosenMenu=$(printf '%s\n%s\n%s\n%s' \
+    "$MenuOpen" "$MenuCreate" "$MenuEdit" "$MenuDelete" \
+    | dmenu -i -l 10 -p "$ScriptName:")
 
 # Open bookmark:
 if [ "$ChosenMenu" = "$MenuOpen" ]; then
-	# Prompt user for bookmark:
-	Chosen=$(printf "%s" "$FormattedBookmarks" \
-		| dmenu -i -l 30 -p "Open:" \
-		| awk '{printf $1}')
-	Chosen="$(printf "%s" "$Bookmarks" \
-		| grep -w ^$Chosen \
-		| awk '{printf $2}')"
-	[ -z "$Chosen" ] && exit 1
+    # Prompt user for bookmark:
+    Chosen=$(printf '%s' "$FormattedBookmarks" \
+        | dmenu -i -l 30 -p 'Open:' \
+        | awk '{printf $1}')
+    Chosen=$(printf '%s' "$Bookmarks" \
+        | grep -w ^$Chosen \
+        | awk '{printf $2}')
+    [ -z "$Chosen" ] && exit 1
 
-	# Open browser with selected URL.
-	$BROWSER "$Chosen"
+    # Open browser with selected URL.
+    $BROWSER "$Chosen"
 
 # Create bookmark:
 elif [ "$ChosenMenu" = "$MenuCreate" ]; then
-	# Get the name of the active window:
-	ActiveWindow="$(ps -p "$(xdotool getwindowfocus getwindowpid)" -o comm=)"
+    # Get the name of the active window:
+    ActiveWindow=$(ps -p "$(xdotool getwindowfocus getwindowpid)" -o comm=)
 
-	# Set the name if the active window is a chromium based browser:
-	printf "%s" "$ActiveWindow" | grep -Eq "chromium|chrome|brave" \
-		&& ActiveWindow="chromium-based"
-	### Haven't actually checked whether Chromium's window name is chromium.
+    # Set the name if the active window is a chromium based browser:
+    printf '%s' "$ActiveWindow" | grep -Eq 'chromium|chrome|brave' \
+        && ActiveWindow='chromium-based'
+    ### Haven't actually checked whether Chromium's window name is chromium.
 
-	# Get URL/title based on browser:
-	if [ "$ActiveWindow" = "qutebrowser" ]; then
-		xdotool search --name qutebrowser key --clearmodifiers y P
-		sleep 0.1
-		URL="$(xclip -o)"
-		sleep 0.1
-		xdotool search --name qutebrowser key --clearmodifiers y T
-		sleep 0.1
-		Title="$(xclip -o)"
-	elif [ "$ActiveWindow" = "chromium-based" ]; then
-		xdotool key --clearmodifiers ctrl+l
-		sleep 0.1
-		xdotool key --clearmodifiers ctrl+c
-		sleep 0.1
-		URL="$(xclip -o)"
-		sleep 0.1
-		### Maybe write it to a file in the background to speed it up.
-		### Doesn't work for some generated sites.
-		Title="$(curl -s "$URL" \
-			| awk -F "<title>|</title>" '{for(i=2;i<=NF;i+=2){print $i}}' \
-			RS="" \
-			| recode html)"
-	fi
+    # Get URL/title based on browser:
+    if [ "$ActiveWindow" = 'qutebrowser' ]; then
+        xdotool search --name qutebrowser key --clearmodifiers y P
+        sleep 0.1
+        URL=$(xclip -o)
+        sleep 0.1
+        xdotool search --name qutebrowser key --clearmodifiers y T
+        sleep 0.1
+        Title=$(xclip -o)
+    elif [ "$ActiveWindow" = 'chromium-based' ]; then
+        xdotool key --clearmodifiers ctrl+l
+        sleep 0.1
+        xdotool key --clearmodifiers ctrl+c
+        sleep 0.1
+        URL=$(xclip -o)
+        sleep 0.1
+        ### Maybe write it to a file in the background to speed it up.
+        ### Doesn't work for some generated sites.
+        Title=$(curl -s "$URL" \
+            | awk -F '<title>|</title>' '{for(i=2;i<=NF;i+=2){print $i}}' \
+            RS='' \
+            | recode html)
+    fi
 
-	# Check if URL already exists.
-	if [ "$URL" ] && grep -q "$URL" "$1" ;then
-		printf "" | dmenu -p "ERROR: URL already bookmarked."
-		exit 1
-	fi
+    # Check if URL already exists.
+    if [ "$URL" ] && grep -q "$URL" "$1" ;then
+        printf '' | dmenu -p 'ERROR: URL already bookmarked.'
+        exit 1
+    fi
 
-	# Prompt user to edit the URL:
-	EditedURL="$(printf "%s" "$URL" | dmenu -l 1 -p "Edit URL:")"
-	[ "$EditedURL" ] && URL="$EditedURL"
+    # Prompt user to edit the URL:
+    EditedURL=$(printf '%s' "$URL" | dmenu -l 1 -p 'Edit URL:')
+    [ "$EditedURL" ] && URL=$EditedURL
 
-	# Prompt user to edit the title:
-	EditedTitle="$(printf "%s" "$Title" | dmenu -l 1 -p "Edit title:")"
-	[ "$EditedTitle" ] && Title="$EditedTitle"
+    # Prompt user to edit the title:
+    EditedTitle=$(printf '%s' "$Title" | dmenu -l 1 -p 'Edit title:')
+    [ "$EditedTitle" ] && Title=$EditedTitle
 
-	# Prompt the user to pick tags for the bookmark:
-	AllTags="$(printf "%s" "$Bookmarks" \
-		| awk -F '\t' '{print $4}' \
-		| tr ',' '\n' \
-		| sort \
-		| uniq)"
-	while true; do
-		SelectedTag="$(printf "%s" "$AllTags" \
-			| dmenu -i -l 30 \
-			-p "Add tags. SHIFT+ENTER to create a new tag. $Tags")"
-		[ -z "$SelectedTag" ] && break
-		Tags="$Tags$SelectedTag,"
-	done
-	Tags="${Tags%?}"
+    # Prompt the user to pick tags for the bookmark:
+    AllTags=$(printf '%s' "$Bookmarks" \
+        | awk -F '\t' '{print $4}' \
+        | tr ',' '\n' \
+        | sort \
+        | uniq)
+    while true; do
+        SelectedTag=$(printf '%s' "$AllTags" \
+            | dmenu -i -l 30 \
+            -p "Add tags. SHIFT+ENTER to create a new tag. $Tags")
+        [ -z "$SelectedTag" ] && break
+        Tags="$Tags$SelectedTag,"
+    done
+    Tags=${Tags%?}
 
-	# Create a preview for the user to see their input:
-	Confirmation="$(printf "%s\nURL: %s\nTitle: %s\nTags: %s" \
-		"This is a preview. Press ENTER to confirm or ESCAPE to cancel." \
-		"$URL" "$Title" "$Tags" \
-		| dmenu -i -l 10)"
+    # Create a preview for the user to see their input:
+    Confirmation=$(printf '%s\nURL: %s\nTitle: %s\nTags: %s' \
+        'This is a preview. Press ENTER to confirm or ESCAPE to cancel.' \
+        "$URL" "$Title" "$Tags" \
+        | dmenu -i -l 10)
 
-	# If the user pressed ENTER, create the bookmark:
-	[ "$Confirmation" ] && \
-		printf "%s\t%s\t%s" \
-		"$URL" "$Title" "$Tags" >> "$1"
+    # If the user pressed ENTER, create the bookmark:
+    [ "$Confirmation" ] && \
+        printf '%s\t%s\t%s' \
+        "$URL" "$Title" "$Tags" >> "$1"
 
 # Edit bookmark:
 elif [ "$ChosenMenu" = "$MenuEdit" ]; then
-	# Prompt user for bookmark:
-	Chosen=$(printf "%s" "$FormattedBookmarks" \
-		| dmenu -i -l 30 -p "Edit:" \
-		| awk '{printf $1}')
-	Chosen="$(printf "%s" "$Bookmarks" \
-		| grep -w ^$Chosen \
-		| awk '{printf $2}')"
-	[ -z "$Chosen" ] && exit 1
+    # Prompt user for bookmark:
+    Chosen=$(printf '%s' "$FormattedBookmarks" \
+        | dmenu -i -l 30 -p "Edit:" \
+        | awk '{printf $1}')
+    Chosen=$(printf '%s' "$Bookmarks" \
+        | grep -w ^$Chosen \
+        | awk '{printf $2}')
+    [ -z "$Chosen" ] && exit 1
 
-	# Get the bookmark information:
-	Mark="$(grep "$Chosen" "$1")"
-	OldURL="$(printf "%s" "$Mark" | awk -F '\t' '{printf $1}')"
-	OldTitle="$(printf "%s" "$Mark" | awk -F '\t' '{printf $2}')"
-	OldTags="$(printf "%s" "$Mark" | awk -F '\t' '{printf $3}')"
+    # Get the bookmark information:
+    Mark=$(grep "$Chosen" "$1")
+    OldURL=$(printf '%s' "$Mark" | awk -F '\t' '{printf $1}')
+    OldTitle=$(printf '%s' "$Mark" | awk -F '\t' '{printf $2}')
+    OldTags=$(printf '%s' "$Mark" | awk -F '\t' '{printf $3}')
 
-	# Prompt user to edit the URL:
-	EditedURL="$(printf "%s" "$OldURL" | dmenu -l 1 -p "Edit URL:")"
-	[ "$EditedURL" ] && URL="$EditedURL"
+    # Prompt user to edit the URL:
+    EditedURL=$(printf '%s' "$OldURL" | dmenu -l 1 -p 'Edit URL:')
+    [ "$EditedURL" ] && URL=$EditedURL
 
-	# Prompt user to edit the title:
-	EditedTitle="$(printf "%s" "$OldTitle" | dmenu -l 1 -p "Edit title:")"
-	[ "$EditedTitle" ] && Title="$EditedTitle"
+    # Prompt user to edit the title:
+    EditedTitle=$(printf '%s' "$OldTitle" | dmenu -l 1 -p 'Edit title:')
+    [ "$EditedTitle" ] && Title=$EditedTitle
 
-	# Prompt the user to pick tags for the bookmark:
-	AllTags="$(printf "%s" "$Bookmarks" \
-		| awk -F '\t' '{print $4}' \
-		| tr ',' '\n' \
-		| sort \
-		| uniq)"
-	while true; do
-		SelectedTag="$(printf "%s" "$AllTags" \
-			| dmenu -i -l 30 \
-			-p "Old: $OldTags | New: $Tags")"
-		[ -z "$SelectedTag" ] && break
-		Tags="$Tags$SelectedTag,"
-	done
-	Tags="${Tags%,}"
+    # Prompt the user to pick tags for the bookmark:
+    AllTags=$(printf '%s' "$Bookmarks" \
+        | awk -F '\t' '{print $4}' \
+        | tr ',' '\n' \
+        | sort \
+        | uniq)
+    while true; do
+        SelectedTag=$(printf '%s' "$AllTags" \
+            | dmenu -i -l 30 \
+            -p "Old: $OldTags | New: $Tags")
+        [ -z "$SelectedTag" ] && break
+        Tags="$Tags$SelectedTag,"
+    done
+    Tags=${Tags%,}
 
-	# Create a preview for the user to see their input:
-	Confirmation="$(printf \
-		"%s\nNew URL: %s\nOld URL: %s\nNew title: %s\nOld title: %s\
-		\nNew tags: %s\nOld tags: %s" \
-		"This is a preview. Press ENTER to confirm or ESCAPE to cancel." \
-		"$URL" "$OldURL" "$Title" "$OldTitle" "$Tags" "$OldTags" \
-		| dmenu -i -l 10)"
+    # Create a preview for the user to see their input:
+    Confirmation=$(printf \
+        '%s\nNew URL: %s\nOld URL: %s\nNew title: %s\nOld title: %s\
+        \nNew tags: %s\nOld tags: %s' \
+        'This is a preview. Press ENTER to confirm or ESCAPE to cancel.' \
+        "$URL" "$OldURL" "$Title" "$OldTitle" "$Tags" "$OldTags" \
+        | dmenu -i -l 10)
 
-	# If the user pressed ENTER, edit the bookmark:
-	if [ "$Confirmation" ]; then
-		sed "\|$Chosen|d" "$1" > "$TempFile"
-		mv "$TempFile" "$1"
-		printf "%s\t%s\t%s" "$URL" "$Title" "$Tags" >> "$1"
-	else
-		exit 1
-	fi
+    # If the user pressed ENTER, edit the bookmark:
+    if [ "$Confirmation" ]; then
+        sed "\|$Chosen|d" "$1" > "$TempFile"
+        mv "$TempFile" "$1"
+        printf '%s\t%s\t%s' "$URL" "$Title" "$Tags" >> "$1"
+    else
+        exit 1
+    fi
 
 # Delete bookmark:
 elif [ "$ChosenMenu" = "$MenuDelete" ]; then
-	# Prompt user for bookmark:
-	Chosen=$(printf "%s" "$FormattedBookmarks" \
-		| dmenu -i -l 30 -p "Delete:" \
-		| awk '{printf $1}')
-	Chosen="$(printf "%s" "$Bookmarks" \
-		| grep -w ^$Chosen \
-		| awk '{printf $2}')"
-	[ -z "$Chosen" ] && exit 1
+    # Prompt user for bookmark:
+    Chosen=$(printf '%s' "$FormattedBookmarks" \
+        | dmenu -i -l 30 -p 'Delete:' \
+        | awk '{printf $1}')
+    Chosen=$(printf '%s' "$Bookmarks" \
+        | grep -w ^$Chosen \
+        | awk '{printf $2}')
+    [ -z "$Chosen" ] && exit 1
 
-	# Delete selected bookmark from file:
-	sed "\|$Chosen|d" "$1" > "$TempFile"
-	mv "$TempFile" "$1"
+    # Delete selected bookmark from file:
+    sed "\|$Chosen|d" "$1" > "$TempFile"
+    mv "$TempFile" "$1"
 
 elif [ -z "$ChosenMenu" ]; then
-	exit 1
+    exit 1
 else
-	printf "ERROR: invalid selection.\n"
-	exit 1
+    printf 'ERROR: invalid selection.\n'
+    exit 1
 fi
diff --git a/dpass b/dpass
--- a/dpass
+++ b/dpass
@@ -27,10 +27,6 @@
 ScriptName=${0##*/}
 Version=1.0.0
 
-TryHelp() { printf "Try '%s --help' for more information.\n" "$ScriptName"; }
-Err() { printf 'ERROR: %s\n' "$1" 1>&2; }
-
-# Compose the help message:
 HelpMessage="$ScriptName - Version: $Version
 Creator: Alexander Chaplin Braz (http://alexchaplinbraz.com)
 License: MIT
@@ -74,23 +70,26 @@ Examples:
 Pro tip:
 You can also pass a command substitution. My favourite is selecting a random
 file to be used as input. For example:
-	export DPASS_OPTS='-Cf \"\$(find \"\$HOME/notes\" -type f | shuf -n1)\"'
+    export DPASS_OPTS='-Cf \"\$(find \"\$HOME/notes\" -type f | shuf -n1)\"'
 Would find all the files insides the notes directory and select a random one
 to be used for your password generation.
 "
 
+error() { printf 'ERROR: %s\n' "$1" 1>&2; }
+
+suggest_help_and_exit() {
+    printf "Try '%s --help' for more information.\n" "$ScriptName";
+    exit 1
+}
+
 case $1 in
-	-h|--help)
-		printf '%s' "$HelpMessage"; exit 0 ;;
-	-v|--version)
-		printf '%s - Version: %s\n' "$ScriptName" "$Version"; exit 1
-	*|'')
-		printf '%s' "$HelpMessage"; exit 1 ;;
+    -h|--help) printf '%s' "$HelpMessage"; exit 0;;
+    -v|--version) printf '%s - Version: %s\n' "$ScriptName" "$Version"; exit 0;;
 esac
 
 if ! command -v genrepass 1> /dev/null 2>&1; then
-	Err "'genrepass' is required for password generation."
-	exit 1
+    error "'genrepass' is required for password generation."
+    suggest_help_and_exit
 fi
 
 # Get the location of the password store:
@@ -112,96 +111,94 @@ ChosenMenu=$(printf '%b' "$FullMenu" | dmenu -i -l 10 -p "$ScriptName:")
 
 # Copy selected entry to clipboard:
 if [ "$ChosenMenu" = "$MenuCopy" ]; then
-	ChosenPass=$(
-		printf '%s' "$PassList" | dmenu -i -l 30 -p 'Select entry to copy:'
-	)
+    ChosenPass=$(
+        printf '%s' "$PassList" | dmenu -i -l 30 -p 'Select entry to copy:'
+    )
 
-	pass show -c "$ChosenPass"
+    pass show -c "$ChosenPass"
 
 # Create new entry/Edit existing entry:
 elif [ "$ChosenMenu" = "$MenuCreate" ]; then
-	ChosenName=$(
-		printf '%s' "$PassList" | dmenu -i -l 30 -p 'Input entry name:'
-	)
+    ChosenName=$(
+        printf '%s' "$PassList" | dmenu -i -l 30 -p 'Input entry name:'
+    )
 
-	[ -z "$ChosenName" ] && exit 1
+    [ -z "$ChosenName" ] && exit 1
 
-	# Set menu options:
-	TypeGenrepass='1. Generate password with genrepass.'
-	TypeSingleLine='2. Write a single line of content.'
+    # Set menu options:
+    TypeGenrepass='1. Generate password with genrepass.'
+    TypeSingleLine='2. Write a single line of content.'
 
-	# Prompt user to choose content type:
-	ChosenType=$(
-		printf '%s\n%s' "$TypeGenrepass" "$TypeSingleLine" \
-			| dmenu -i -l 10 -p 'Select content type:'
-	)
+    # Prompt user to choose content type:
+    ChosenType=$(
+        printf '%s\n%s' "$TypeGenrepass" "$TypeSingleLine" \
+            | dmenu -i -l 10 -p 'Select content type:'
+    )
 
-	# Generate password with genrepass:
-	if [ "$ChosenType" = "$TypeGenrepass" ];then
+    # Generate password with genrepass:
+    if [ "$ChosenType" = "$TypeGenrepass" ];then
 
-		# Set genrepass options:
-		if [ -z "$1" ]; then
-			if [ -n "$DPASS_OPTS" ]; then
-				GRPargs=$DPASS_OPTS
-			else
-				GRPargs='-sC'
-			fi
-		else
-			GRPargs=$1
-		fi
+        # Set genrepass options:
+        if [ -z "$1" ]; then
+            if [ -n "$DPASS_OPTS" ]; then
+                GRPargs=$DPASS_OPTS
+            else
+                GRPargs='-sC'
+            fi
+        else
+            GRPargs=$1
+        fi
 
-		# Keep generating passwords until one is selected:
-		while [ -z "$Content" ]; do
-			Content=$(
-				eval genrepass "$GRPargs" | dmenu -l 10 \
-					-p 'ENTER to select, ESCAPE to generate new password:'
-			)
-		done
+        # Keep generating passwords until one is selected:
+        while [ -z "$Content" ]; do
+            Content=$(
+                eval genrepass "$GRPargs" | dmenu -l 10 \
+                    -p 'ENTER to select, ESCAPE to generate new password:'
+            )
+        done
 
-	# Input custom single line content:
-	elif [ "$ChosenType" = "$TypeSingleLine" ];then
-		Content=$(printf '' | dmenu -p 'Input content:')
+    # Input custom single line content:
+    elif [ "$ChosenType" = "$TypeSingleLine" ];then
+        Content=$(printf '' | dmenu -p 'Input content:')
 
-	elif [ -z "$ChosenType" ];then
-		exit 1
-	else
-		Err 'Invalid selection.'
-		TryHelp
-		exit 1
-	fi
+    elif [ -z "$ChosenType" ];then
+        exit 1
+    else
+        error 'Invalid selection.'
+        suggest_help_and_exit
+    fi
 
-	# Create a preview for the user to see their input:
-	Confirmation=$(
-		printf '%s\nEntry: %s\nContent: %s' \
-			'This is a preview. Press ENTER to confirm or ESCAPE to cancel.' \
-			"$ChosenName" "$Content" | dmenu -i -l 10
-	)
+    # Create a preview for the user to see their input:
+    Confirmation=$(
+        printf '%s\nEntry: %s\nContent: %s' \
+            'This is a preview. Press ENTER to confirm or ESCAPE to cancel.' \
+            "$ChosenName" "$Content" | dmenu -i -l 10
+    )
 
-	# If the user pressed ENTER, create/edit the entry:
-	if [ "$Confirmation" ]; then
-		printf '%s' "$Content" | pass add --echo --force "$ChosenName"
-	fi
+    # If the user pressed ENTER, create/edit the entry:
+    if [ "$Confirmation" ]; then
+        printf '%s' "$Content" | pass add --echo --force "$ChosenName"
+    fi
 
 # Open entry with $EDITOR:
 elif [ "$ChosenMenu" = "$MenuEdit" ]; then
-	ChosenPass=$(
-		printf '%s' "$PassList" | dmenu -i -l 30 -p "Select entry to edit:"
-	)
+    ChosenPass=$(
+        printf '%s' "$PassList" | dmenu -i -l 30 -p "Select entry to edit:"
+    )
 
-	$TERMINAL -e pass edit "$ChosenPass"
+    $TERMINAL -e pass edit "$ChosenPass"
 
 # Delete an entry:
 elif [ "$ChosenMenu" = "$MenuDelete" ]; then
-	ChosenPass=$(
-		printf '%s' "$PassList" | dmenu -i -l 30 -p 'Select entry to delete:'
-	)
+    ChosenPass=$(
+        printf '%s' "$PassList" | dmenu -i -l 30 -p 'Select entry to delete:'
+    )
 
-	pass delete --force "$ChosenPass"
+    pass delete --force "$ChosenPass"
 
 elif [ -z "$ChosenMenu" ]; then
-	exit 1
+    exit 1
 else
-	Err 'Invalid selection.'
-	TryHelp
-	exit 1
+    error 'Invalid selection.'
+    suggest_help_and_exit
 fi
