Switched from tabs to spaces.

diff --git a/genrepass b/genrepass
--- a/genrepass
+++ b/genrepass
@@ -61,8 +61,8 @@ ScriptName=${0##*/}
 Version=1.1.2
 
 suggest_help_and_exit() {
-	printf "Try '%s --help' for more information.\n" "$ScriptName" 1>&2
-	exit 1
+    printf "Try '%s --help' for more information.\n" "$ScriptName" 1>&2
+    exit 1
 }
 
 HelpMessage="$ScriptName - Version: $Version
@@ -148,129 +148,129 @@ Options:
 # Read as: check argument ($2) for these types in option $1.
 # Requires shifting afterwards.
 check_arg() {
-	if printf '%s' "$1" | grep -qE '^\+?[[:digit:]]+$';then
-		Type='positive integer'
-	elif printf '%s' "$1" | grep -qE '^-[[:digit:]]+$';then
-		Type='negative integer'
-	elif printf '%s' "$1" | grep -qE '^\+?[[:digit:]]*\.?([[:digit:]]+)$';then
-		Type='positive float'
-	elif printf '%s' "$1" | grep -qE '^-[[:digit:]]*\.?([[:digit:]]+)$';then
-		Type='negative float'
-	elif printf '%s' "$1" | grep -qE '^[[:alpha:]]+$';then
-		Type='alphabetic'
-	elif printf '%s' "$1" | grep -qE '^[[:alnum:]]+$';then
-		Type='alphanumeric'
-	elif printf '%s' "$1" | grep -qE '^--?[[:alpha:]]+$' || [ -z "$1" ];then
-		Missing=true
-	else
-		Type='UNKNOWN'
-	fi
+    if printf '%s' "$1" | grep -qE '^\+?[[:digit:]]+$';then
+        Type='positive integer'
+    elif printf '%s' "$1" | grep -qE '^-[[:digit:]]+$';then
+        Type='negative integer'
+    elif printf '%s' "$1" | grep -qE '^\+?[[:digit:]]*\.?([[:digit:]]+)$';then
+        Type='positive float'
+    elif printf '%s' "$1" | grep -qE '^-[[:digit:]]*\.?([[:digit:]]+)$';then
+        Type='negative float'
+    elif printf '%s' "$1" | grep -qE '^[[:alpha:]]+$';then
+        Type='alphabetic'
+    elif printf '%s' "$1" | grep -qE '^[[:alnum:]]+$';then
+        Type='alphanumeric'
+    elif printf '%s' "$1" | grep -qE '^--?[[:alpha:]]+$' || [ -z "$1" ];then
+        Missing=true
+    else
+        Type='UNKNOWN'
+    fi
 
-	ExpectedType=$(printf '%s' "$2" | sed 's/|/ or /g')
+    ExpectedType=$(printf '%s' "$2" | sed 's/|/ or /g')
 
-	if [ $Missing ]; then
-		printf "MISSING ARGUMENT: option '%s' expects %s.\n" \
-			"$3" "$ExpectedType" 1>&2
-		suggest_help_and_exit
-	elif ! printf '%s' "$Type" | grep -qE "$2"; then
-		printf "TYPE ERROR: '%s' expects %s, got %s '%s'.\n" \
-			"$3" "$ExpectedType" "$Type" "$1" 1>&2
-		suggest_help_and_exit
-	fi
+    if [ $Missing ]; then
+        printf "MISSING ARGUMENT: option '%s' expects %s.\n" \
+            "$3" "$ExpectedType" 1>&2
+        suggest_help_and_exit
+    elif ! printf '%s' "$Type" | grep -qE "$2"; then
+        printf "TYPE ERROR: '%s' expects %s, got %s '%s'.\n" \
+            "$3" "$ExpectedType" "$Type" "$1" 1>&2
+        suggest_help_and_exit
+    fi
 }
 
 # Parse parameters:
 while [ "$#" -gt 0 ]; do
-	case $1 in
-		-[[:alpha:]][[:alpha:]]*|-[[:alpha:]][[:digit:]]*)
-			opts=$(printf '%s' "$1" \
-				| sed 's/-//;s/[[:alpha:]]/ -&/g;s/-[[:alpha:]]/& /g')
-			shift
-			set -- $opts "$@"
-			continue;;
-		-h|--help) printf '%s' "$HelpMessage"; exit 0;;
-		-v|--version) printf '%s\n' "$Version"; exit 0;;
-		-d|--debug) Debug=true;;
-		-s|--use-source) UseSource=true;;
-		-c|--clipboard) CopyToClipboard=true;;
-		-C|--capitalize) Capitalize=true;;
-		-r|--replace) Replace=true;;
-		-t|--translate-accents) TransAccents=true;;
-		-R|--max-resets) check_arg "$2" 'positive integer' "$1"
-			MaxResets=$2; shift;;
-		-l|--min-pass-len) check_arg "$2" 'positive integer' "$1"
-			MinPassLen=$2; shift;;
-		-L|--max-pass-len) check_arg "$2" 'positive integer' "$1"
-			MaxPassLen=$2; shift;;
-		-N|--num-amount) check_arg "$2" 'positive integer' "$1"
-			NumAmount=$2; shift;;
-		-P|--spechars-amount) check_arg "$2" 'positive integer' "$1"
-			SpeCharsAmount=$2; shift;;
-		-S|--spechars) SpeChars=$2; shift;;
-		-A|--upper-amount) check_arg "$2" 'positive integer' "$1"
-			UpperAmount=$2; shift;;
-		-a|--lower-amount) check_arg "$2" 'positive integer' "$1"
-			LowerAmount=$2; shift;;
-		-F|--force-upper) ForceUpper=true;;
-		-f|--force-lower) ForceLower=true;;
-		-x|--fixed-pass-len) check_arg "$2" 'positive integer' "$1"
-			FixedPassLen=$2; shift;;
-		-U|--unforce-upper) UnForceUpper=true;;
-		-u|--unforce-lower) UnForceLower=true;;
-		-[[:alpha:]]|--[[:alpha:]]*)
-			printf "ERROR: unknown option '%s'\n" "$1" 1>&2
-			suggest_help_and_exit;;
-		*) 	if [ "$FilePath" ]; then
-				printf "ERROR: can't set file twice.\n" 1>&2
-				suggest_help_and_exit
-			elif [ ! -f "$1" ]; then
-				printf 'ERROR: not a file.\n' 1>&2
-				suggest_help_and_exit
-			elif [ ! -s "$1" ]; then
-				printf 'ERROR: file is empty.\n' 1>&2
-				suggest_help_and_exit
-			else
-				FilePath="$1"
-			fi;;
-	esac
-	shift
+    case $1 in
+        -[[:alpha:]][[:alpha:]]*|-[[:alpha:]][[:digit:]]*)
+            opts=$(printf '%s' "$1" \
+                | sed 's/-//;s/[[:alpha:]]/ -&/g;s/-[[:alpha:]]/& /g')
+            shift
+            set -- $opts "$@"
+            continue;;
+        -h|--help) printf '%s' "$HelpMessage"; exit 0;;
+        -v|--version) printf '%s\n' "$Version"; exit 0;;
+        -d|--debug) Debug=true;;
+        -s|--use-source) UseSource=true;;
+        -c|--clipboard) CopyToClipboard=true;;
+        -C|--capitalize) Capitalize=true;;
+        -r|--replace) Replace=true;;
+        -t|--translate-accents) TransAccents=true;;
+        -R|--max-resets) check_arg "$2" 'positive integer' "$1"
+            MaxResets=$2; shift;;
+        -l|--min-pass-len) check_arg "$2" 'positive integer' "$1"
+            MinPassLen=$2; shift;;
+        -L|--max-pass-len) check_arg "$2" 'positive integer' "$1"
+            MaxPassLen=$2; shift;;
+        -N|--num-amount) check_arg "$2" 'positive integer' "$1"
+            NumAmount=$2; shift;;
+        -P|--spechars-amount) check_arg "$2" 'positive integer' "$1"
+            SpeCharsAmount=$2; shift;;
+        -S|--spechars) SpeChars=$2; shift;;
+        -A|--upper-amount) check_arg "$2" 'positive integer' "$1"
+            UpperAmount=$2; shift;;
+        -a|--lower-amount) check_arg "$2" 'positive integer' "$1"
+            LowerAmount=$2; shift;;
+        -F|--force-upper) ForceUpper=true;;
+        -f|--force-lower) ForceLower=true;;
+        -x|--fixed-pass-len) check_arg "$2" 'positive integer' "$1"
+            FixedPassLen=$2; shift;;
+        -U|--unforce-upper) UnForceUpper=true;;
+        -u|--unforce-lower) UnForceLower=true;;
+        -[[:alpha:]]|--[[:alpha:]]*)
+            printf "ERROR: unknown option '%s'\n" "$1" 1>&2
+            suggest_help_and_exit;;
+        *)  if [ "$FilePath" ]; then
+                printf "ERROR: can't set file twice.\n" 1>&2
+                suggest_help_and_exit
+            elif [ ! -f "$1" ]; then
+                printf 'ERROR: not a file.\n' 1>&2
+                suggest_help_and_exit
+            elif [ ! -s "$1" ]; then
+                printf 'ERROR: file is empty.\n' 1>&2
+                suggest_help_and_exit
+            else
+                FilePath="$1"
+            fi;;
+    esac
+    shift
 done
 
 if [ $Debug ]; then
-	printf 'Debug Mode\n\n'
-	printf 'Replace: %s\n' $Replace
-	printf 'Capitalize: %s\n' $Capitalize
-	printf 'UseSource: %s\n' $UseSource
-	printf 'FilePath: %s\n' "$FilePath"
-	printf 'CopyToClipboard: %s\n' $CopyToClipboard
-	printf 'MaxResets: %s\n' $MaxResets
-	printf 'MinPassLen: %s\n' $MinPassLen
-	printf 'MaxPassLen: %s\n' $MaxPassLen
-	printf 'FixedPassLen: %s\n' $FixedPassLen
-	printf 'NumAmount: %s\n' $NumAmount
-	printf 'SpeCharsAmount: %s\n' $SpeCharsAmount
-	printf 'SpeChars: %s\n' "$SpeChars"
-	printf 'Debug: %s\n' $Debug
-	printf 'TransAccents: %s\n' $TransAccents
-	printf 'UpperAmount: %s\n' $UpperAmount
-	printf 'LowerAmount: %s\n' $LowerAmount
-	printf 'ForceUpper: %s\n' $ForceUpper
-	printf 'ForceLower: %s\n' $ForceLower
-	printf 'UnForceUpper: %s\n' $UnForceUpper
-	printf 'UnForceLower: %s\n' $UnForceLower
+    printf 'Debug Mode\n\n'
+    printf 'Replace: %s\n' $Replace
+    printf 'Capitalize: %s\n' $Capitalize
+    printf 'UseSource: %s\n' $UseSource
+    printf 'FilePath: %s\n' "$FilePath"
+    printf 'CopyToClipboard: %s\n' $CopyToClipboard
+    printf 'MaxResets: %s\n' $MaxResets
+    printf 'MinPassLen: %s\n' $MinPassLen
+    printf 'MaxPassLen: %s\n' $MaxPassLen
+    printf 'FixedPassLen: %s\n' $FixedPassLen
+    printf 'NumAmount: %s\n' $NumAmount
+    printf 'SpeCharsAmount: %s\n' $SpeCharsAmount
+    printf 'SpeChars: %s\n' "$SpeChars"
+    printf 'Debug: %s\n' $Debug
+    printf 'TransAccents: %s\n' $TransAccents
+    printf 'UpperAmount: %s\n' $UpperAmount
+    printf 'LowerAmount: %s\n' $LowerAmount
+    printf 'ForceUpper: %s\n' $ForceUpper
+    printf 'ForceLower: %s\n' $ForceLower
+    printf 'UnForceUpper: %s\n' $UnForceUpper
+    printf 'UnForceLower: %s\n' $UnForceLower
 fi
 
 # Get the text to use for password generation:
 if [ $UseSource ] && [ "$FilePath" ]; then
-	printf "ERROR: can't use source and provide a file at the same time.\n" 1>&2
-	suggest_help_and_exit
+    printf "ERROR: can't use source and provide a file at the same time.\n" 1>&2
+    suggest_help_and_exit
 elif [ $UseSource ]; then
-	Text=$(cat "$0")
+    Text=$(cat "$0")
 elif [ "$FilePath" ]; then
-	Text=$(cat "$FilePath")
+    Text=$(cat "$FilePath")
 else
-	printf 'ERROR: no file was provided.\n' 1>&2
-	suggest_help_and_exit
+    printf 'ERROR: no file was provided.\n' 1>&2
+    suggest_help_and_exit
 fi
 
 # Calculate the correct MaxPassLen if inserting:
@@ -283,29 +283,29 @@ fi
 
 # Check that MaxPassLen isn't lower than MinPassLen:
 [ $MaxPassLen -lt $MinPassLen ] && \
-	printf "INVALID ARGUMENTS: '%s' can't be lower than '%s'.\n" \
-		'--max-pass-len' '--min-pass-len' 1>&2 && \
-	exit 1
+    printf "INVALID ARGUMENTS: '%s' can't be lower than '%s'.\n" \
+        '--max-pass-len' '--min-pass-len' 1>&2 && \
+    exit 1
 
 # Set fixed password length if set:
 if [ $FixedPassLen ]; then
-	[ ! $Replace ] && MaxPassLen=$((FixedPassLen - SpeCharsAmount - NumAmount))
-	[ $Replace ] && MaxPassLen=$FixedPassLen
-	[ ! $Replace ] && MinPassLen=$((FixedPassLen - SpeCharsAmount - NumAmount))
-	[ $Replace ] && MinPassLen=$FixedPassLen
+    [ ! $Replace ] && MaxPassLen=$((FixedPassLen - SpeCharsAmount - NumAmount))
+    [ $Replace ] && MaxPassLen=$FixedPassLen
+    [ ! $Replace ] && MinPassLen=$((FixedPassLen - SpeCharsAmount - NumAmount))
+    [ $Replace ] && MinPassLen=$FixedPassLen
 fi
 
 # Get rid of accents on characters so they aren't lost:
 if [ $TransAccents ]; then
-	[ "$(uchardet "$FilePath")" = 'UTF-8' ] && Text=$(printf '%s' "$Text" \
-		| iconv -f UTF-8 -t ASCII//TRANSLIT)
+    [ "$(uchardet "$FilePath")" = 'UTF-8' ] && Text=$(printf '%s' "$Text" \
+        | iconv -f UTF-8 -t ASCII//TRANSLIT)
 fi
 
 # Separate every word to a new numbered line and only keep [A-Za-z]:
 CleanText=$(printf '%s' "$Text" \
-	| tr -cd '\12\40\101-\132\141-\172' \
-	| tr -s ' ' '\n' \
-	| nl -n ln)
+    | tr -cd '\12\40\101-\132\141-\172' \
+    | tr -s ' ' '\n' \
+    | nl -n ln)
 
 # Total amount of words:
 TextWC=$(printf '%s' "$CleanText" | wc -l)
@@ -315,122 +315,122 @@ index=$(shuf -i 1-$TextWC -n1)
 
 # Generate the word-only password:
 while true ; do
-	if [ $Capitalize ]; then
-		Password=$Password$(printf '%s' "$CleanText" \
-		| grep -w ^$index \
-		| awk '{printf $2}' \
-		| sed 's/./\U&/')
-		[ $Debug ] && printf '%s\n' "$Password"
-	else
-		Password=$Password$(printf '%s' "$CleanText" \
-		| grep -w ^$index \
-		| awk '{printf $2}')
-		[ $Debug ] && printf '%s\n' "$Password"
-	fi
-	[ $ResetCounter -ge $MaxResets ] && \
-		Password=$(expr substr "$Password" 1 $MaxPassLen)
-	[ ${#Password} -gt $MaxPassLen ] && Password=""
-	[ -z "$Password" ] && ResetCounter=$((ResetCounter + 1))
-	[ ${#Password} -ge $MinPassLen ] && break
-	index=$((index + 1))
-	[ $index -gt $TextWC ] && index=1
+    if [ $Capitalize ]; then
+        Password=$Password$(printf '%s' "$CleanText" \
+        | grep -w ^$index \
+        | awk '{printf $2}' \
+        | sed 's/./\U&/')
+        [ $Debug ] && printf '%s\n' "$Password"
+    else
+        Password=$Password$(printf '%s' "$CleanText" \
+        | grep -w ^$index \
+        | awk '{printf $2}')
+        [ $Debug ] && printf '%s\n' "$Password"
+    fi
+    [ $ResetCounter -ge $MaxResets ] && \
+        Password=$(expr substr "$Password" 1 $MaxPassLen)
+    [ ${#Password} -gt $MaxPassLen ] && Password=""
+    [ -z "$Password" ] && ResetCounter=$((ResetCounter + 1))
+    [ ${#Password} -ge $MinPassLen ] && break
+    index=$((index + 1))
+    [ $index -gt $TextWC ] && index=1
 done
 
 [ $Debug ] && \
-	printf '\n%s <-- Character Count: %s\n' \
-	"$Password" ${#Password}
+    printf '\n%s <-- Character Count: %s\n' \
+    "$Password" ${#Password}
 
 # Generate random, non-repeated positions so that the same characters
 # aren't replaced more than once:
 if [ $Replace ]; then
-	Positions=$(shuf -i \
-		1-${#Password} \
-		-n$((SpeCharsAmount + NumAmount)) \
-		| nl -n ln)
-	[ $Debug ] && printf '\n%s\n' "$Positions"
+    Positions=$(shuf -i \
+        1-${#Password} \
+        -n$((SpeCharsAmount + NumAmount)) \
+        | nl -n ln)
+    [ $Debug ] && printf '\n%s\n' "$Positions"
 fi
 
 # Function for adding characters:
 add_char() {
-	if [ "$1" = 'special' ]; then
-		charAmount=$SpeCharsAmount
-		getChar='expr substr "$SpeChars" $(shuf -i 1-${#SpeChars} -n1) 1'
-		grepArg='^$((index + 1))'
-	elif [ "$1" = 'number' ]; then
-		charAmount=$NumAmount
-		getChar='shuf -i 0-9 -n1'
-		grepArg='^$((index + 1 + SpeCharsAmount))'
-	fi
+    if [ "$1" = 'special' ]; then
+        charAmount=$SpeCharsAmount
+        getChar='expr substr "$SpeChars" $(shuf -i 1-${#SpeChars} -n1) 1'
+        grepArg='^$((index + 1))'
+    elif [ "$1" = 'number' ]; then
+        charAmount=$NumAmount
+        getChar='shuf -i 0-9 -n1'
+        grepArg='^$((index + 1 + SpeCharsAmount))'
+    fi
 
-	index=0
-	while [ $index -lt $charAmount ]; do
-		char=$(eval "$getChar")
-		if [ $Replace ]; then
-			pos=$(printf '%s' "$Positions" \
-				| grep -w $grepArgs \
-				| awk '{printf $2}')
-			[ $Debug ] && printf '%s at %s  ' "$char" $pos
-			Password=$(printf '%s' "$Password" \
-				| sed s/./"$char"/$pos)
-		else
-			pos=$(shuf -i 1-${#Password} -n1)
-			[ $Debug ] && printf '%s at %s  ' "$char" $pos
-			Password=$(printf '%s' "$Password" \
-				| sed s/./"$char"\&/$pos)
-		fi
-		index=$((index + 1))
-	done
+    index=0
+    while [ $index -lt $charAmount ]; do
+        char=$(eval "$getChar")
+        if [ $Replace ]; then
+            pos=$(printf '%s' "$Positions" \
+                | grep -w $grepArgs \
+                | awk '{printf $2}')
+            [ $Debug ] && printf '%s at %s  ' "$char" $pos
+            Password=$(printf '%s' "$Password" \
+                | sed s/./"$char"/$pos)
+        else
+            pos=$(shuf -i 1-${#Password} -n1)
+            [ $Debug ] && printf '%s at %s  ' "$char" $pos
+            Password=$(printf '%s' "$Password" \
+                | sed s/./"$char"\&/$pos)
+        fi
+        index=$((index + 1))
+    done
 }
 
 # Add special characters to the password:
 add_char special
 
 [ $Debug ] && \
-	printf '\n%s <-- Character Count: %s\n' \
-	"$Password" ${#Password}
+    printf '\n%s <-- Character Count: %s\n' \
+    "$Password" ${#Password}
 
 # Add numbers to the password:
 add_char number
 
 [ $Debug ] && \
-	printf '\n%s <-- Character Count: %s\n' \
-	"$Password" ${#Password}
+    printf '\n%s <-- Character Count: %s\n' \
+    "$Password" ${#Password}
 
 # Function for changing capitalization:
 change_case_to() {
-	if [ "$1" = 'upper' ]; then
-		forceState=$ForceUpper
-		caseAmount=$UpperAmount
-		grepClass='[[:lower:]]'
-		trString1='[:lower:]'
-		trString2='[:upper:]'
-		toCase='Upper'
-	elif [ "$1" = 'lower' ]; then
-		forceState=$ForceLower
-		caseAmount=$LowerAmount
-		grepClass='[[:upper:]]'
-		trString1='[:upper:]'
-		trString2='[:lower:]'
-		toCase='Lower'
-	fi
+    if [ "$1" = 'upper' ]; then
+        forceState=$ForceUpper
+        caseAmount=$UpperAmount
+        grepClass='[[:lower:]]'
+        trString1='[:lower:]'
+        trString2='[:upper:]'
+        toCase='Upper'
+    elif [ "$1" = 'lower' ]; then
+        forceState=$ForceLower
+        caseAmount=$LowerAmount
+        grepClass='[[:upper:]]'
+        trString1='[:upper:]'
+        trString2='[:lower:]'
+        toCase='Lower'
+    fi
 
-	index=1
-	while [ $forceState ] && [ $index -le $caseAmount ]; do
-		pos=$(shuf -i 1-${#Password} -n1)
-		char=$(expr substr "$Password" $pos 1)
-		[ $Debug ] && printf '\n%s at %s' "$char" $pos
-		if printf '%s' "$char" | grep -q "$grepClass"; then
-			char=$(printf '%s' "$char" | tr "$trString1" "$trString2")
-			[ $Debug ] && printf '\n%s at %s <-- To %s' "$char" $pos "$toCase"
-			Password=$(printf '%s' "$Password" \
-				| sed s/./"$char"/$pos)
-			[ $Debug ] && printf '\n%s' "$Password"
-			index=$((index + 1))
-		elif ! printf '%s' "$Password" | grep -q "$grepClass"; then
-			[ $Debug ] && printf '\nAll characters are uppercase\n'
-			break
-		fi
-	done
+    index=1
+    while [ $forceState ] && [ $index -le $caseAmount ]; do
+        pos=$(shuf -i 1-${#Password} -n1)
+        char=$(expr substr "$Password" $pos 1)
+        [ $Debug ] && printf '\n%s at %s' "$char" $pos
+        if printf '%s' "$char" | grep -q "$grepClass"; then
+            char=$(printf '%s' "$char" | tr "$trString1" "$trString2")
+            [ $Debug ] && printf '\n%s at %s <-- To %s' "$char" $pos "$toCase"
+            Password=$(printf '%s' "$Password" \
+                | sed s/./"$char"/$pos)
+            [ $Debug ] && printf '\n%s' "$Password"
+            index=$((index + 1))
+        elif ! printf '%s' "$Password" | grep -q "$grepClass"; then
+            [ $Debug ] && printf '\nAll characters are uppercase\n'
+            break
+        fi
+    done
 }
 
 # Calculate the amount of uppercase letters:
@@ -459,7 +459,7 @@ change_case_to lower
 
 # Output resulting password:
 if [ $CopyToClipboard ]; then
-	printf '%s' "$Password" | xclip -selection clipboard
+    printf '%s' "$Password" | xclip -selection clipboard
 elif [ ! $Debug ]; then
-	printf '%s' "$Password"
+    printf '%s' "$Password"
 fi
