Improved options.
Rewrote the whole parameter parsing with no known limitations.
Implemented an error checking system.
Sent all error messages to stderr.
No need to use -f for specifying file.
Changed some short options to make more sense.

diff --git a/genrepass b/genrepass
--- a/genrepass
+++ b/genrepass
@@ -56,12 +56,12 @@ ForceLower=
 UnForceUpper=
 UnForceLower=
 ResetCounter=0
-Version=1.0.1
+Version=1.1.1
 Password=""
 ScriptName="${0##*/}"
 
 suggest_help() {
-	printf "Try '%s --help' for more information.\n" "$ScriptName"
+	printf "Try '%s --help' for more information.\n" "$ScriptName" 1>&2
 }
 
 HelpMessage="$ScriptName - Version: $Version
@@ -69,7 +69,7 @@ Creator: Alexander Chaplin Braz (http://alexchaplinbraz.com)
 License: MIT
 
 Usage:
-    $ScriptName [opts] {-f <path> | --file <path> | -s | --use-source} [opts]
+    $ScriptName [opts] {filepath} [opts]
 
 Examples:
 Use the script's own source code, capitalize every word and copy to clipboard:
@@ -77,11 +77,12 @@ Use the script's own source code, capitalize every word and copy to clipboard:
 
 Use the file \"Journal-2020.md\", translate all accented characters, capitalize
 every word and copy to clipboard:
-    $ScriptName -tCcf \"\$HOME/Documents/Journal-2020.md\"
+    $ScriptName -tCc \"\$HOME/Documents/Journal-2020.md\"
 
 Use the script's own source code, containing 10 special characters and
-with a length between 30 and 50 characters:
-    $ScriptName -s --min-pass-len 30 --max-pass-len 50 --spechars-amount 10
+with a length between 30 and 40 characters:
+    $ScriptName -s --min-pass-len 30 --max-pass-len 40 --spechars-amount 10
+    $ScriptName -s -l 30 -L 40 -P 10
 
 Options:
     -h | --help                  Display this help message and exit.
@@ -99,147 +100,144 @@ Options:
     -t | --translate-accents     Translate accented characters to their normal
                                  forms, thus keeping them from being parsed out.
                                  Only works for UTF-8 encoded files.
-    -f <path> | --file <path>    Specify a file to use for password generation.
-    -A | --max-resets <num>      Maximum amount of resets before the password
+    -R | --max-resets <num>      Maximum amount of resets before the password
                                  is trimmed to the maximum password length.
                                  Default: $MaxResets
-    -B | --min-pass-len <num>    Minumum password length.
+    -l | --min-pass-len <num>    Minumum password length.
                                  Default: $MinPassLen
-    -N | --max-pass-len <num>    Maximum password length.
+    -L | --max-pass-len <num>    Maximum password length.
                                  Default: $MaxPassLen
-    -D | --num-amount <num>      Amount of numbers to insert.
+    -N | --num-amount <num>      Amount of numbers to insert.
                                  Default: $NumAmount
-    -E | --spechars-amount <num> Amount of special characters to insert.
+    -P | --spechars-amount <num> Amount of special characters to insert.
                                  Default: $SpeCharsAmount
-    -F | --spechars <chars>      List of special characters to insert.
+    -S | --spechars <chars>      List of special characters to insert.
                                  Avoid using '&' and '$' due to them messing
                                  up the script and $ being interpreted as a
                                  variable in the shell.
                                  Default: $SpeChars
-    -G | --upper-amount <num>    Amount of letters to be capitalized.
+    -A | --upper-amount <num>    Amount of letters to be capitalized.
                                  Default: $UpperAmount
-    -H | --lower-amount <num>    Amount of letters to be decapitalized.
+    -a | --lower-amount <num>    Amount of letters to be decapitalized.
                                  Default: $LowerAmount
-    -I | --force-upper           Force the password to have a number of
+    -F | --force-upper           Force the password to have a number of
                                  uppercase letters, based on '--upper-amount'.
                                  Gets automatically turned on if there are
                                  no uppercase letters at all.
-    -J | --force-lower           Force the password to have a number of
+    -f | --force-lower           Force the password to have a number of
                                  lowercase letters, based on '--lower-amount'.
                                  Gets automatically turned on if there are
                                  no lowercase letters at all.
-    -K | --fixed-pass-len <num>  Instead of getting a password with a random
+    -x | --fixed-pass-len <num>  Instead of getting a password with a random
                                  length in a certain range, specify it.
                                  This option overrides '--min-pass-len'
                                  and '--max-pass-len'.
-    -L | --unforce-upper         Prevent the automatic capitalization when
+    -U | --unforce-upper         Prevent the automatic capitalization when
                                  there are no uppercase letters.
                                  Gets ignored if '--force-upper' is set.
-    -M | --unforce-lower         Prevent the automatic decapitalization when
+    -u | --unforce-lower         Prevent the automatic decapitalization when
                                  there are no lowercase letters.
                                  Gets ignored if '--force-lower' is set.
 "
 
-# Translate the long options into short options for getopts:
-reset=true
-for arg in "$@"
-do
-	if [ $reset ]; then
-		unset reset
-		set --
+# Check argument for type and existence.
+# Usage: check_arg "$2" "type1|type2|type3" "$1"
+# Where $1 is the option and $2 is the argument.
+# Read as: check argument ($2) for these types in option $1.
+# Requires shifting afterwards.
+check_arg() {
+	if printf "%s" "$1" | grep -qE '^\+?[[:digit:]]+$';then
+		Type="positive integer"
+	elif printf "%s" "$1" | grep -qE '^-[[:digit:]]+$';then
+		Type="negative integer"
+	elif printf "%s" "$1" | grep -qE '^\+?[[:digit:]]*\.?([[:digit:]]+)$';then
+		Type="positive float"
+	elif printf "%s" "$1" | grep -qE '^-[[:digit:]]*\.?([[:digit:]]+)$';then
+		Type="negative float"
+	elif printf "%s" "$1" | grep -qE '^[[:alpha:]]+$';then
+		Type="alphabetic"
+	elif printf "%s" "$1" | grep -qE '^[[:alnum:]]+$';then
+		Type="alphanumeric"
+	elif printf "%s" "$1" | grep -qE '^--?[[:alpha:]]+$' || [ -z "$1" ];then
+		Missing=true
+	else
+		Type="UNKNOWN"
 	fi
-	case "$arg" in
-		--help) set -- "$@" -h;;
-		--version) set -- "$@" -v;;
-		--debug) set -- "$@" -d;;
-		--use-source) set -- "$@" -s;;
-		--clipboard) set -- "$@" -c;;
-		--capitalize) set -- "$@" -C;;
-		--replace) set -- "$@" -r;;
-		--file) set -- "$@" -f;;
-		--translate-accents) set -- "$@" -t;;
-		--max-resets) set -- "$@" -A;;
-		--min-pass-len) set -- "$@" -B;;
-		--max-pass-len) set -- "$@" -N;;
-		--num-amount) set -- "$@" -D;;
-		--spechars-amount) set -- "$@" -E;;
-		--spechars) set -- "$@" -F;;
-		--upper-amount) set -- "$@" -G;;
-		--lower-amount) set -- "$@" -H;;
-		--force-upper) set -- "$@" -I;;
-		--force-lower) set -- "$@" -J;;
-		--fixed-pass-len) set -- "$@" -K;;
-		--unforce-upper) set -- "$@" -L;;
-		--unforce-lower) set -- "$@" -M;;
-		*) set -- "$@" "$arg";;
-	esac
-done
 
-# Function for getting the '-short | --long':
-shtong() {
-	case "$1" in
-		h) printf "%s" "-h | --help";;
-		v) printf "%s" "-v | --version";;
-		d) printf "%s" "-d | --debug";;
-		s) printf "%s" "-s | --use-source";;
-		c) printf "%s" "-c | --clipboard";;
-		C) printf "%s" "-C | --capitalize";;
-		r) printf "%s" "-r | --replace";;
-		f) printf "%s" "-f | --file";;
-		t) printf "%s" "-t | --translate-accents";;
-		A) printf "%s" "-A | --max-resets";;
-		B) printf "%s" "-B | --min-pass-len";;
-		N) printf "%s" "-N | --max-pass-len";;
-		D) printf "%s" "-D | --num-amount";;
-		E) printf "%s" "-E | --spechars-amount";;
-		F) printf "%s" "-F | --spechars";;
-		G) printf "%s" "-G | --upper-amount";;
-		H) printf "%s" "-H | --lower-amount";;
-		I) printf "%s" "-I | --force-upper";;
-		J) printf "%s" "-J | --force-lower";;
-		K) printf "%s" "-K | --fixed-pass-len";;
-		L) printf "%s" "-L | --unforce-upper";;
-		M) printf "%s" "-M | --unforce-lower";;
-		*) printf "%s" "$1"
-	esac
+	ExpectedType="$(printf "%s" "$2" | sed 's/|/ or /g')"
+
+	if [ $Missing ]; then
+		printf "MISSING ARGUMENT: option '%s' expects %s.\n" \
+			"$3" "$ExpectedType" 1>&2
+		suggest_help
+		exit 1
+	elif ! printf "%s" "$Type" | grep -qE "$2"; then
+		printf "TYPE ERROR: '%s' expects %s, got %s '%s'.\n" \
+			"$3" "$ExpectedType" "$Type" "$1" 1>&2
+		suggest_help
+		exit 1
+	fi
 }
 
-# Parse the options:
-while getopts ":hvdscCrf:tA:B:N:D:E:F:G:H:IJK:LM" opt; do
-	case "$opt" in
-		h)	printf "%s" "$HelpMessage"
-			exit;;
-		v)	printf "%s - Version %s\n" "$ScriptName" "$Version"
-			exit;;
-		d)	Debug=true;;
-		s)	UseSource=true;;
-		c)	CopyToClipboard=true;;
-		C)	Capitalize=true;;
-		r)	Replace=true;;
-		f)	FilePath="$OPTARG";;
-		t)	TransAccents=true;;
-		A)	MaxResets=$OPTARG;;
-		B)	MinPassLen=$OPTARG;;
-		N)	MaxPassLen=$OPTARG;;
-		D)	NumAmount=$OPTARG;;
-		E)	SpeCharsAmount=$OPTARG;;
-		F)	SpeChars="$OPTARG";;
-		G)	UpperAmount=$OPTARG;;
-		H)	LowerAmount=$OPTARG;;
-		I)	ForceUpper=true;;
-		J)	ForceLower=true;;
-		K)	FixedPassLen=$OPTARG;;
-		L)	UnForceUpper=true;;
-		M)	UnForceLower=true;;
-		\?)	printf "INVALID OPTION: '-%s'\n" "$OPTARG"
+# Parse parameters:
+while [ "$#" -gt 0 ]; do
+	case $1 in
+		### Character classes don't seem to work here.
+		-[a-zA-Z][a-zA-Z]*)
+			opts=$(printf "%s" "$1" | sed 's/./ -&/g;s/\ --\ //')
+			shift
+			set -- $opts "$@"
+			continue;;
+		-h|--help) printf "%s" "$HelpMessage"; exit 0;;
+		-v|--version) printf "%s" "$HelpMessage"; exit 0;;
+		-d|--debug) Debug=true;;
+		-s|--use-source) UseSource=true;;
+		-c|--clipboard) CopyToClipboard=true;;
+		-C|--capitalize) Capitalize=true;;
+		-r|--replace) Replace=true;;
+		-t|--translate-accents) TransAccents=true;;
+		-R|--max-resets) check_arg "$2" "positive integer" "$1"
+			MaxResets=$2; shift;;
+		-l|--min-pass-len) check_arg "$2" "positive integer" "$1"
+			MinPassLen=$2; shift;;
+		-L|--max-pass-len) check_arg "$2" "positive integer" "$1"
+			MaxPassLen=$2; shift;;
+		-N|--num-amount) check_arg "$2" "positive integer" "$1"
+			NumAmount=$2; shift;;
+		-P|--spechars-amount) check_arg "$2" "positive integer" "$1"
+			SpeCharsAmount=$2; shift;;
+		-S|--spechars) SpeChars=$2; shift;;
+		-A|--upper-amount) check_arg "$2" "positive integer" "$1"
+			UpperAmount=$2; shift;;
+		-a|--lower-amount) check_arg "$2" "positive integer" "$1"
+			LowerAmount=$2; shift;;
+		-F|--force-upper) ForceUpper=true;;
+		-f|--force-lower) ForceLower=true;;
+		-x|--fixed-pass-len) check_arg "$2" "positive integer" "$1"
+			FixedPassLen=$2; shift;;
+		-U|--unforce-upper) UnForceUpper=true;;
+		-u|--unforce-lower) UnForceLower=true;;
+		-*) printf "ERROR: unknown option '%s'\n" "$1" 1>&2
 			suggest_help
 			exit 1;;
-		:)	printf "MISSING ARGUMENT for option '%s'\n" "$(shtong "$OPTARG")"
-			suggest_help
-			exit 1;;
+		*) 	if [ "$FilePath" ]; then
+				printf "ERROR: can't set file twice.\n" 1>&2
+				suggest_help
+				exit 1
+			elif [ ! -f "$1" ]; then
+				printf "ERROR: not a file.\n" 1>&2
+				suggest_help
+				exit 1
+			elif [ ! -s "$1" ]; then
+				printf "ERROR: file is empty.\n" 1>&2
+				suggest_help
+				exit 1
+			else
+				FilePath="$1"
+			fi;;
 	esac
+	shift
 done
-shift $((OPTIND - 1))
 
 if [ $Debug ]; then
 	printf "Debug Mode\n\n"
@@ -267,16 +265,15 @@ fi
 
 # Get the text to use for password generation:
 if [ $UseSource ] && [ "$FilePath" ]; then
-	printf "ERROR: Can't use source and provide a file at the same time.\n"
+	printf "ERROR: can't use source and provide a file at the same time.\n" 1>&2
 	suggest_help
 	exit 1
 elif [ $UseSource ]; then
 	Text="$(cat "$0")"
 elif [ "$FilePath" ]; then
 	Text="$(cat "$FilePath")"
-	[ -z "$Text" ] && printf "ERROR: File is empty." && exit 1
 else
-	printf "ERROR: No file was provided.\n"
+	printf "ERROR: no file was provided.\n" 1>&2
 	suggest_help
 	exit 1
 fi
@@ -292,7 +289,7 @@ fi
 # Check that MaxPassLen isn't lower than MinPassLen:
 [ $MaxPassLen -lt $MinPassLen ] && \
 	printf "INVALID ARGUMENTS: '%s' can't be lower than '%s'.\n" \
-		"$(shtong N)" "$(shtong B)" && \
+		"--max-pass-len" "--min-pass-len" 1>&2 && \
 	exit 1
 
 # Set fixed password length if set:
